name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install
        run: |
            pip install mkdocs
            pip install mkdocs-material

      - name: Deploy
        run: |
            mkdocs build
            pip install awscli
            ls -lhat
            aws s3 cp site s3://baniol-mkdocs-resources/ --recursive
        working-directory: ./mkdocs
   